#!/usr/bin/env ruby

# set load path to be relative to the calling script
$: << File.join(File.expand_path(File.dirname($0)), 'lib')
$: << File.join(File.expand_path(File.dirname($0)), 'config')

# set Gemfile to be relative to the calling script
ENV['BUNDLE_GEMFILE'] = File.join(File.expand_path(File.dirname($0)), 'Gemfile')

require 'bundler'
Bundler.setup

require 'aggregator'
Aggregator.start
